### ISSUE TITLE
Support wrapped tokens like `WETH`, `WPOL`, `wstETH` etc.

### ISSUE THREAD

**Issue by MbBrainz** [0xa3k5/web3icons#45]
symbols like `WETH`, `WPOL`, `wstETH` are currently not supported, while they are very common.

**Comment by 0xa3k5** [comment]
wrapped tokens are tricky, the appendix differs and every token can be wrapped and live on any chain. If you intend to just represent them with the token's icon, I suggest passing the "parent" token name to the web3icons instead of the wrapped token. Because supporting the wrapped tokens doesn't end with those 3, it could just bloat the library. You can simply remove the `w` from the `wEth` and pass it as `eth` on your consumer app to get the `eth` icon.
